# Build using -> 
# docker build -t aritz-backend:latest -f Dockerfile.backend .
#
# Execute the Dockerfile.backend using ->
# docker run -it -p 3000:3000 --rm aritz-backend:latest 

FROM golang:1.19.4 as backend_compiler
WORKDIR /src/
COPY . .
RUN go build -o /app/webapi/ ./cmd/webapi
FROM debian:stable
WORKDIR /app/
COPY --from=backend_compiler /app/webapi ./
RUN mkdir -p ./uploads && chmod 777 ./uploads
EXPOSE 3000
CMD ["/app/webapi"]