# Build using -> 
# docker build -t aritz-frontend:latest -f Dockerfile.frontend .
#
# Execute the Dockerfile.frontend using ->
# docker run -it -p 8080:8080 --rm aritz-frontend:latest

FROM node:20 as frontend_compiler
WORKDIR /webui
COPY webui/ .
RUN yarn install && yarn run build-prod
FROM nginx:latest
COPY --from=frontend_compiler /webui/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
RUN chmod -R 777 /var/cache/nginx /var/run /var/log/nginx
EXPOSE 8080