# Build using -> 
# docker build -t aritz-frontend:latest -f Dockerfile.frontend .
#
# Execute the Dockerfile.frontend using ->
# docker run -it -p 8080:80 --rm aritz-frontend:latest

FROM node:20 as frontend_compiler
WORKDIR /webui
COPY webui/ .
RUN yarn install && yarn build
FROM nginx:latest
COPY --from=frontend_compiler /webui/dist /usr/share/nginx/html
EXPOSE 80