# Build using -> 
# docker build -t aritz-backend:latest -f Dockerfile.backend .
#
# Execute the Dockerfile.backend using ->
# docker run -it -p 3000:3000 --rm aritz-backend:latest (*)

FROM golang:1.19.4 as backend_compiler
RUN mkdir /Executable/
WORKDIR /GoFiles/
COPY . .
RUN go build -o /Executable/ ./cmd/webapi

FROM debian:stable
WORKDIR /executable_backend/
COPY --from=backend_compiler /Executable/ .
EXPOSE 3000
CMD ["./webapi"]