openapi: 3.0.3
info:
  title: WASAText API
  description: >
    API for the **WASAText** messaging application, which allows users to send and receive 
    individual or group messages with support for text, photos, and reactions.  
    Includes simplified login, user management, conversations, messages, and group handling.
  version: 1.0.0
security:
  - BearerAuth: []

paths:
  /session:
    post:
      tags: ["login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        '201':
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  identifier:
                    # change here if you decide to use an integer
                    # or any other type of identifier
                    type: string
                    example: "abcdef012345"
  /me/username:
    put:
      summary: Updates the current user's name
      operationId: setMyUserName
      responses:
  /me/photo:
    put:
      summary: Updates the current user's profile photo
      operationId: setMyPhoto
      responses:
  /conversations:
    get:
      summary: Retrieves all conversations of the user
      operationId: getMyConversations
      responses:
  /conversations/{conversationId}:
    get:
      summary: Retrieves a specific conversation
      operationId: getConversation
      responses:
  /conversations/{conversationId}/messages:
    post:
      summary: Sends a new message
      operationId: sendMessage
      responses:
  /conversations/{conversationId}/messages/{messageId}/comments:
    post:
      summary: Forwards an existing message
      operationId: forwardMessage
      responses:
    delete:
      summary: Removes a reaction (comment) from a message
      operationId: uncommentMessage
      responses:
  /conversations/{conversationId}/messages/{messageId}:
    delete:
      summary: Deletes a sent message
      operationId: deleteMessage
      responses:
  /groups/{groupId}/users:
    post:
      summary: Adds a user to the group
      operationId: addToGroup
      responses:

  

